[package]
name = "realtime_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
redis = { version = "0.29", features = ["tokio-comp"] }
tokio = { version = "1.44.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
